keys:
  - &nixlab age1fgugkzpt620qzcufv6fnv7y0awra7q26cxmlcnnhnhm28gt4xyuq2tl8sg
  - &sysbofh age1nps4uakty7t5zmuyxcr3cm94zcnq29js3zeterg5cvgzmvkzeq6qajmqx7
  - &minix age1lserw975kwpncu87jm2qy4vcsnw7j0qqt686kkg7plgaftl5z4tq5d3mgh

creation_rules:
  - path_regex: hosts/nixlab/secrets.yaml$
    key_groups:
      - age:
          - *nixlab

  - path_regex: hosts/sysbofh/secrets.yaml$
    key_groups:
      - age:
          - *sysbofh

  - path_regex: hosts/minix/secrets.yaml$
    key_groups:
      - age:
          - *minix
