keys:
  - &nixlab age1cghjdfqq08yuj22p89k2v8xv3dxzmsn5jrav7es86er30vyhharq5mr4ud
  - &sysbofh age1nps4uakty7t5zmuyxcr3cm94zcnq29js3zeterg5cvgzmvkzeq6qajmqx7

creation_rules:
  - path_regex: hosts/nixlab/secrets.yaml$
    key_groups:
    - age:
      - *nixlab

  - path_regex: hosts/sysbofh/secrets.yaml$
    key_groups:
    - age:
      - *sysbofh
