-- sysBOFH

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- monitor=,preferred,auto,1
-- https://wiki.hyprland.org/FAQ/#workspaces-or-clients-are-disappearing-or-monitor-related-dispatchers-cause-crashes
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "Unknown-1",
	disabled = true,
})

-- New monitor Dell 27" 4k setup
--## (embedded DisplayPort)
hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "0x0",
	scale = "1",
})

--## External new monitor
hl.monitor({
	output = "DP-1",
	mode = "preferred",
	position = "1920x0",
	scale = "1.75",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch
-- swayidle/swaylock - commented for hyprlock/hypridle migration
--exec-once = swayidle -w before-sleep 'swaylock -f -c 000000 --clock --indicator --indicator-radius 100 --ring-color 808080'
--exec-once = swayidle -w timeout 1800 'swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 25x25 --effect-vignette 0.5:0.5 --ring-color 808080 --key-hl-color 880033 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --fade-in 0.2'

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- Set programs that you use
local terminal = "ghostty"
local fileManager = "thunar"
local menu = "rofi -show drun"

-- Some default env vars.
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("NIXOS_OZONE_WL", "1")

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 7,
	bezier = "myBezier",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 7,
	bezier = "default",
	style = "popin 80%",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "borderangle",
	enabled = true,
	speed = 8,
	bezier = "default",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 7,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 6,
	bezier = "default",
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("brave"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("code"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("cider"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("todoist-electron"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd('brave --force-device-scale-factor="1.1" --incognito'))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("Telegram"))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exec_cmd("slack"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("Vial"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("procalc"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + SHIFT + M", function()
	local w = hl.get_active_workspace()
	if not w then
		return
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "desc:Dell Inc. DELL S2725QS F1PC364" }))
end)

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.resize({ x = -60, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 60, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -60, relative = true }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.resize({ x = 0, y = 60, relative = true }))

hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill -SIGUSR2 waybar"))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + PERIOD", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + COMMA", hl.dsp.focus({ workspace = "-1" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("volumectl -u up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("volumectl -u down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("volumectl toggle-mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("volumectl -m toggle-mute"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("lightctl up"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("lightctl down"))

hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

local saveto = "\"$HOME/Media/SS/$(date +'%d%b%Y_%H%M%S')-$(hostname).png\""
local screenshotarea = "hyprctl eval 'hl.animation({ leaf = \"fadeOut\", enabled = false })'; grimblast --notify copysave area "
	.. saveto
	.. '; hyprctl eval \'hl.animation({ leaf = "fadeOut", enabled = true, speed = 4, bezier = "default" })\''
hl.bind("print", hl.dsp.exec_cmd("grimblast --notify copysave screen " .. saveto))
hl.bind("CTRL + print", hl.dsp.exec_cmd("grimblast --notify --cursor copysave active " .. saveto))
hl.bind("CTRL + SHIFT + print", hl.dsp.exec_cmd(screenshotarea .. " " .. saveto))

hl.bind("mouse:274", hl.dsp.exec_cmd(";"))

hl.window_rule({
	match = {
		class = "thunar",
	},
	opacity = "0.8 0.8",
})

hl.window_rule({
	match = {
		class = "org.pulseaudio.pavucontrol",
	},
	opacity = "0.8 0.8",
})

hl.window_rule({
	match = {
		class = "Cider",
	},
	opacity = "0.8 0.8",
})

hl.window_rule({
	match = {
		class = ".blueman-manager-wrapped",
	},
	opacity = "0.8 0.8",
})

hl.window_rule({
	match = {
		class = "obsidian",
	},
	opacity = "0.8 0.8",
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "altgr-intl",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
		},
		sensitivity = 0, -- -1.0 to 1.0, 0 means no modification.
	},
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 3,
		gaps_out = 5,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		layout = "dwindle",
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
	},
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 10,
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
		},
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},
	},
	animations = {
		enabled = true,
		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
	dwindle = {
		-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
		preserve_split = true,
	},
	master = {
		-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
		new_status = "master",
	},
	-- Gestures - workspace swipe with 3 fingers
	-- https://wiki.hypr.land/Configuring/Gestures/
	gestures = {
		workspace_swipe_distance = 200,
	},
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		key_press_enables_dpms = true,
		mouse_move_enables_dpms = true,
	},
	-- Example per-device config
	-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
	-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
	-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
	-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
	-- Move current workspace to my external monitor (Docking Station)
	-- Move focus with mainMod + arrow keys
	-- Moving windows
	-- Window resizing                           X  Y
	-- Waybar
	-- Switch workspaces with mainMod + [0-9]
	-- Navigate to the next and previous workspaces
	-- NOTE: Without 'e' navigate for all empty workspaces
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	-- Example special workspace (scratchpad)
	-- Scroll through existing workspaces with mainMod + scroll
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- Disable cursor "when typing"
	cursor = {
		inactive_timeout = 2,
	},
	-- Multimedia
	--bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
	--bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
	--bindl=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	--bindl=, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
	-- Brightness control
	--bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
	--bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
	-- Testing "avizo"
	-- Lock screen
	--bind = $mainMod, L, exec, swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 25x25 --effect-vignette 0.5:0.5 --ring-color 808080 --key-hl-color 880033 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --fade-in 0.2
	-- Screenshots
	-- Disable paste with middle button (trackbar)
	-- Transparency rules
})

hl.on("hyprland.start", function()
	hl.exec_cmd("$POLKIT_BIN")
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("avizo-service")
	hl.exec_cmd("~/.config/hypr/scripts/awww-random.sh ~/wallpapers/")
	hl.exec_cmd("sleep 5; waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css")
	hl.exec_cmd("sleep 6; blueman-applet")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("sleep 12; mullvad-vpn")
	hl.exec_cmd("sleep 10; trayscale --hide-window")
end)
